### ISSUE TITLE
Add dataset: cultural_heritage_metadata_accuracy

### ISSUE THREAD

**Issue by davanstrien** [bigscience-workshop/lam#27]
### A URL for this dataset

https://figshare.com/articles/dataset/Annotated_dataset_to_assess_the_accuracy_of_the_textual_description_of_cultural_heritage_records/13359104

### Dataset description

From the description of the dataset: 

> "The dataset contains more than 100K textual descriptions of cultural items from Cultura Italia (http://www.culturaitalia.it/opencms/index.jsp?language=en), the Italian National Cultural aggregator. Each of the description is labeled either HIGH or LOW quality, according its adherence to the standard cataloguing guidelines provided by Istituto Centrale per il Catalogo e la Documentazione (ICCD). More precisely, each description is labeled as HIGH quality if the object and subject of the item (for which the description is provided) are both described according to the ICCD guidelines, and as LOW quality in all other cases. Most of the dataset was manually annotated, with ~30K descriptions automatically labeled as LOW quality due to their length (less than 3 tokens) or their provenance from old (pre-2012), not curated, collections. The dataset was developed to support the training and testing of ML text classification approaches for automatically assessing the quality of textual descriptions in digital Cultural Heritage repositories."

This is a nice dataset for inclusion because it deals with a practical task that is of interest to many LAM organizations (assessing metadata quality). It is also a nice (non-English) dataset that can be used for evaluating text classification models. 

### Dataset modality

Text

### Dataset licence

Creative Commons Attribution 4.0 International

### How can you access this data

As a download from a repository/website

### Confirm the dataset has an open licence

- [X] To the best of my knowledge, this dataset is accessible via an open licence

**Comment by clancyoftheoverflow** [comment]
Thank you @davanstrien Daniel for your suggestion. I have reviewed your candidate dataset and I added it to dataset for upload. 😄

**Comment by davanstrien** [comment]
#self-assign

**Comment by albertvillanova** [comment]
#self-assign

**Comment by davanstrien** [comment]
#self-assign

**Comment by davanstrien** [comment]
#ready-for-review

**Comment by davanstrien** [comment]
I decided to implement this as a dataset script so I had more control over the loading process. I've also made an initial attempt at the DataCard based on the paper describing the dataset.

**Comment by cakiki** [comment]
This looks great; thank you for adding the dataset :heart:
