### ISSUE TITLE
Add dataset: brill_iconclass

### ISSUE THREAD

**Issue by davanstrien** [bigscience-workshop/lam#30]
### A URL for this dataset

https://labs.brill.com/ictestset/

### Dataset description

A test dataset and challenge to apply machine learning to collections described with the [Iconclass](https://iconclass.org/) classification system. 

[Iconclass](https://iconclass.org/) is a metadata standard used by some LAM institutions. This dataset is of particular interest for the following reasons:

- the dataset includes images relevant to the LAM domain (art history) 
- some images contain multiple iconclass labels whilst others contain a single one
- the iconclass schema itself poses an interesting machine learning challenge since the notation of the schema is broken down into parts. This means that whilst the dataset can be used as a image classification dataset is likely to benefit from more bespoke sequence prediction approaches. 

### Dataset modality

Image

### Dataset licence

Creative Commons Public Domain Dedication and Certification

### How can you access this data

As a download from a repository/website

### Confirm the dataset has an open licence

- [X] To the best of my knowledge, this dataset is accessible via an open licence

### Contact details for data custodian

posthumus@brill.com

**Comment by cakiki** [comment]
Looks great! Removing the candidate tag :smiley:

**Comment by davanstrien** [comment]
#self-assign

**Comment by davanstrien** [comment]
#ready-for-review

**Comment by davanstrien** [comment]
I have written a script for loading this one: https://huggingface.co/datasets/biglam/cultural_heritage_metadata_accuracy

@albertvillanova I didn't make this one streaming. I did have a version that supported streaming but it was quite a bit slower to load. It's possible I missed something obvious though. 

I used the following to generate examples in the streaming version: 
```python
    def _generate_examples(self, download_dir):
        with ZipFile(download_dir) as myzip:
            with myzip.open("data.json") as json_file:
                data = json.load(json_file)
                for row, item in enumerate(data.items()):
                    filepath, labels = item
                    image = Image.open(myzip.open(filepath))
                    yield row, {"image": image, "label": labels}
```
My own feeling is that streaming is less important for this one but if I've missed an obvious way of supporting streaming happy to hear it!

**Comment by epoz** [comment]
BTW, I am not affiliated with Brill any more, so my contact address should be updated. You can use info@iconclass.org for testset related matters.

**Comment by epoz** [comment]
Is it an idea to add the [core data of the Iconclass system](https://github.com/iconclass/data) as a dataset?

**Comment by davanstrien** [comment]
> BTW, I am not affiliated with Brill any more, so my contact address should be updated. You can use [info@iconclass.org](mailto:info@iconclass.org) for testset related matters.

I will update that 🙂

**Comment by davanstrien** [comment]
> Is it an idea to add the [core data of the Iconclass system](https://github.com/iconclass/data) as a dataset?

That would be great. I had originally planned to also add a configuration of this dataset that had the 'translation' of the iconclass labels i.e. turing the iconclass code into the associated description. I know there used to be a Python library that allowed for these queries but I think it's no longer maintained? Adding the core data as a dataset would both be nice as its own dataset but could also potentially be used as a way of doing this 'translation'.

**Comment by epoz** [comment]
Ouch, yes. [that Python library](https://pypi.org/project/ICONCLASS/) was also made by me, but has terrible (read: non-existent) documentation.
Would love to update it, but there have been other things clamouring for attention.

If there is interest in using it, will galvanise me to give it some spit-and-polish.

**Comment by epoz** [comment]
I have updated the location of this testset, it is now on:
https://iconclass.org/testset/

**Comment by davanstrien** [comment]
> I have updated the location of this testset, it is now on: [iconclass.org/testset](https://iconclass.org/testset/)

Thanks for letting me know — just updated the URLs.
