### ISSUE TITLE
Add dataset: atypical_animacy

### ISSUE THREAD

**Issue by davanstrien** [bigscience-workshop/lam#38]
### A URL for this dataset

https://doi.org/10.23636/1215

### Dataset description

> Atypical animacy detection dataset, based on nineteenth-century sentences in English extracted from an open dataset of nineteenth-century books digitized by the British Library (available via https://doi.org/10.21250/db14, British Library Labs, 2014). This dataset contains 598 sentences containing mentions of machines. Each sentence has been annotated according to the animacy and humanness of the machine in the sentence. 

### Dataset modality

Text

### Dataset licence

Creative Commons Zero v1.0 Universal

### How can you access this data

As a download from a repository/website

### Confirm the dataset has an open licence

- [X] To the best of my knowledge, this dataset is accessible via an open licence

**Comment by shamikbose** [comment]
#self-assign

**Comment by shamikbose** [comment]
I implemented this as a script to preprocess some of the information that was added to annotate the data. The data aso includes offsets of the target text in the sentence, which was missing from the original dataset. All offsets have been tested to make sure they are the same as the target text

**Comment by shamikbose** [comment]
#ready-for-review

**Comment by albertvillanova** [comment]
Thanks for your contribution @shamikbose.

First of all: could you please transfer the repo to the biglam organization namespace?
- We are adding all datasets under that org
- We have updated the Wiki docs to explain this better
- To do the transfer, please:
  - Go to https://huggingface.co/datasets/shamikbose89/atypical_animacy/settings
  - Under *Rename or transfer this dataset*:
     - As "New owner", select `biglam`
     - As "New name", just write the current dataset name `atypical_animacy`
     - Click "I understand the consequences, move/rename this dataset"
  - Wait some seconds until the transfer is effective

**Comment by shamikbose** [comment]
@albertvillanova The transfer is completed. The new link is https://huggingface.co/datasets/biglam/atypical_animacy

**Comment by albertvillanova** [comment]
Thanks for the addition and the transfer.

The script looks awesome.

Just a last request: would you mind to put the YAML tags in the header of the README file?
- You can use this Space to generate the YAML tags: https://huggingface.co/spaces/huggingface/datasets-tagging
- Once created, just copy-paste the YAML tags (appearing on the right column) to the beginning of the README file, between `---`:
```
---
copy-paste the YAML tags
---

# Dataset Card for atypical_animacy
...

We forgot to put this instruction in the Wiki guide (we are fixing this), but this tags are really important to make the dataset searchable/discoverable on the Hub (see here: https://huggingface.co/datasets).

**Comment by albertvillanova** [comment]
I am also re-running the refresh of the Preview to make it appear nice (I think the transfer broke it).

**Comment by shamikbose** [comment]
@albertvillanova The YAML tags have been added. The Preview is back up. Thanks for re-running it

**Comment by davanstrien** [comment]
Thanks so much for adding this dataset @shamikbose 🚀

**Comment by albertvillanova** [comment]
@shamikbose I have just noticed this among the YAML tags:
```
paperswithcode_id: cnn-daily-mail-1
```

I think this is wrong. As this dataset is not in [Papers with Code](https://paperswithcode.com/), the tag should be set to `null` instead:
```
paperswithcode_id: null
```

**Comment by shamikbose** [comment]
@albertvillanova I made the change. I think it was copied over from a previous YAML I was trying to update
