### ISSUE TITLE
Add dataset: digital_libraries_document_types

### ISSUE THREAD

**Issue by davanstrien** [bigscience-workshop/lam#46]
### A URL for this dataset

https://doi.org/10.6084/m9.figshare.4834229.v2

### Dataset description

> Abstract: In this paper, we address the problem of classifying documents available from the global network of (open access) repositories according to their type. We show that the metadata provided by repositories enabling us to distinguish research papers, thesis and slides are missing in over 60% of cases. While these metadata describing document types are useful in a variety of scenarios ranging from research analytics to improving search and recommender (SR) systems, this problem has not yet been sufficiently addressed in the context of the repositories infrastructure. We have developed a new approach for classifying document types using supervised machine learning based exclusively on text specific features. We achieve 0.96 F1-score using the random forest and Adaboost classifiers, which are the best performing models on our data. By analysing the SR system logs of the CORE digital library aggregator, we show that users are an order of magnitude more likely to click on research papers and thesis than on slides. This suggests that using document types as a feature for ranking/filtering SR results in digital libraries has the potential to improve user experience.

This is mainly of interest as a tabular dataset since the available fields in the datasets are derived features from the original textual data. 

### Dataset modality

Other

### Dataset licence

Creative Commons Attribution 4.0 International

### How can you access this data

As a download from a repository/website

### Confirm the dataset has an open licence

- [X] To the best of my knowledge, this dataset is accessible via an open licence

**Comment by shamikbose** [comment]
For this dataset, if you want to access the actual articles, it looks like you have to register for a Slideshare API (which might be free) and the Core API which has some [terms of use](https://core.ac.uk/terms). Is that still okay to use?

**Comment by davanstrien** [comment]
> For this dataset, if you want to access the actual articles, it looks like you have to register for a Slideshare API (which might be free) and the Core API which has some [terms of use](https://core.ac.uk/terms). Is that still okay to use?

Good spot, I'll have a bit more of a think about this one, but this one is probably a lower priority given that getting at the actual data will be a bit more convoluted. I'll take this off the backlog for now.

**Comment by davanstrien** [comment]
I will close this one for now since it seems like it will be difficult to get the data in an accessible format.
