### ISSUE TITLE
Add dataset: old_bailey_proceedings_online

### ISSUE THREAD

**Issue by davanstrien** [bigscience-workshop/lam#55]
### A URL for this dataset

https://www.dhi.ac.uk/data/oldbailey

### Dataset description

> The dataset consists of 2,163 transcriptions of the Proceedings and 475 Ordinary's Accounts marked up in TEI-XML, and contains some documentation covering the data structure and variables. Each Proceedings file represents one session of the court (1674-1913), and each Ordinary's Account file represents a single pamphlet (1676-1772).

This dataset represents an interesting text corpus for a number of reasons:

- it covers a long time period
- the text data represents court transcriptions of court proceedings. As a result, the text in the corpus can be considered somewhat closer to spoken language for the time period and also represents language use from a broader range of speakers i.e. includes more working-class speech compared to parliamentary corpora (particularly for the earlier periods).

Whilst relatively small, I think this dataset could be a useful component of a training dataset for training historic language models. 

### Dataset modality

Text

### Dataset licence

Creative Commons Attribution 4.0 International

### How can you access this data

As a download from a repository/website

### Confirm the dataset has an open licence

- [X] To the best of my knowledge, this dataset is accessible via an open licence

**Comment by shamikbose** [comment]
#self-assign

**Comment by shamikbose** [comment]
@davanstrien For this dataset, what would be ideally looking to have? There's a lot of extraneous information in these XMLs. Also, what task would this text be used for? There's some NER in the passages
```
<interp inst="OA16760517n12-2" type="given" value="EDWARD"/>Edward Russel</persName> that suffered, were brought 
to this untimely and ignominious End, by the means and seducements of this unhappy Woman. For they together with one A.
 M. going after the former Sessions to a Gentlemans House, to sollicite and engage his Interest, in order to the obtaining of a 
Reprieve for a Woman that past for one of their Wives, and was then under Condemnation, they chanced to spie the Maid a 
scowring a very considerable quantity of Plate, the glittering sight whereof so much affected them, that when they came back 
to <placeName id="OA16760517-geo-8">Newgate</placeName>, to give an account of their business, amongst other 
discourse, they mentioned what abundance of Plate they saw. And will you only see it?
```
but what else would this dataset be used for?

**Comment by davanstrien** [comment]
> @davanstrien For this dataset, what would be ideally looking to have? There's a lot of extraneous information in these XMLs. Also, what task would this text be used for? There's some NER in the passages

I think there are a few potential use cases would be for training and evaluating language models. For this, I think the main features that could be useful to have is the text and associated dates. 

NER would also be a great use case for this, especially as it is 'clean' text rather than OCR which makes it easier to perform an evaluation of the performance of OCR methods across different time periods without also introducing the issue of OCR noise (which is likely to be correlated to time period too). I  think adding NER fields from this text would also be great but I realise this might be a little bit trickier to implement.

For this particular dataset, I think we can also emphasise in the Datacard that we welcome suggestions/pull requests for additional configurations. If you prefer to implement only the simpler ones for now that is also completely fine of course. There may also be some extra XML support being added to the datasets library which could make working with this kind of data simpler (cc @albertvillanova)

also cc'ing @clancyoftheoverflow @cakiki who may have thoughts on this too

**Comment by shamikbose** [comment]
> For this, I think the main features that could be useful to have is the text and associated dates.

Sounds good! I can leave the dates as is and they can be parsed by whoever is using it

> I think adding NER fields from this text would also be great but I realise this might be a little bit trickier to implement.

It shouldn't be too difficult to implement. I will try it out and share them to my HF account and then transfer it to bigLAM after someone's had a chance to look at it

**Comment by davanstrien** [comment]
> > For this, I think the main features that could be useful to have is the text and associated dates.
> 
> Sounds good! I can leave the dates as is and they can be parsed by whoever is using it
> 
> > I think adding NER fields from this text would also be great but I realise this might be a little bit trickier to implement.
> 
> It shouldn't be too difficult to implement. I will try it out and share them to my HF account and then transfer it to bigLAM after someone's had a chance to look at it

That sounds great. Thanks for working on this 🤗

**Comment by shamikbose** [comment]
#ready-for-review

**Comment by shamikbose** [comment]
@davanstrien This dataset is now live at https://huggingface.co/datasets/shamikbose89/old_bailey_proceedings. Can you take a look to check if it looks alright and then I can transfer it to biglam? Thanks!

**Comment by davanstrien** [comment]
> @davanstrien This dataset is now live at [huggingface.co/datasets/shamikbose89/old_bailey_proceedings](https://huggingface.co/datasets/shamikbose89/old_bailey_proceedings). Can you take a look to check if it looks alright and then I can transfer it to biglam? Thanks!

Thanks for this! I am AFK most of today, but I'll take a look at this tomorrow 🙂

**Comment by davanstrien** [comment]
Hi @shamikbose, thanks so much for working on this. Sorry for the slow response with this. I just caught covid, so I'm unable to work much. 

Some initial comments:

- I made a small suggestion in a pull request to fix the `en` language tag
- On https://huggingface.co/datasets/shamikbose89/old_bailey_proceedings/blob/main/old_bailey_proceedings.py#L145, I think it would be better to just log an exception here rather than asking for user input (since this might prevent the loading script from working inside other scripts. WDYT @albertvillanova 
- NIT, you could replace the dictionary here https://huggingface.co/datasets/shamikbose89/old_bailey_proceedings/blob/main/old_bailey_proceedings.py#L42 and just put the URL in a variable 

@shamikbose happy for you to move this over to the BigLAM org. I may make a few minor additions to the README if that's okay with you. @albertvillanova or @clancyoftheoverflow would be great if you could look at this one at some point, too (I trust my brain even less than usual today!) 

thanks again for working on this (and so many other datasets)!

**Comment by davanstrien** [comment]
I've made a few extra changes to the README now. I'll close this for now since I've put a note on the README asking for any suggestions for other configurations in the discussion section of this dataset. Thanks again @shamikbose!
