### ISSUE TITLE
Add dataset: lampeter_corpus

### ISSUE THREAD

**Issue by clancyoftheoverflow** [bigscience-workshop/lam#56]
### A URL for this dataset

https://ota.bodleian.ox.ac.uk/repository/xmlui/handle/20.500.12024/3193

### Dataset description

The Lampeter Corpus of Early Modern English Tracts is a collection of texts on various subject matter published between 1640 and 1740 – a time that is marked by the rise of mass publication, the development of a public discourse in many areas of everyday life and, last but not least, the standardisation of British English. 

Size: 50,797,916 words.

Annotation: no linguistic annotation.

### Dataset modality

Text

### Dataset licence

Other license

### Other licence

Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)

### How can you access this data

As a download from a repository/website

### Confirm the dataset has an open licence

- [X] To the best of my knowledge, this dataset is accessible via an open licence

**Comment by davanstrien** [comment]
thanks for suggesting!

**Comment by shamikbose** [comment]
#self-assign

**Comment by shamikbose** [comment]
@davanstrien @clancyoftheoverflow This dataset is live at https://huggingface.co/datasets/shamikbose89/lampeter_corpus

**Comment by shamikbose** [comment]
@davanstrien @clancyoftheoverflow  Bumping this for review, if you have the bandwidth

**Comment by shamikbose** [comment]
@davanstrien I already merged your changes. I had totally forgotten about the date being an available format for `datasets`. It is now formatted as a `date64` field with the format `%Y`

**Comment by davanstrien** [comment]
> @davanstrien I already merged your changes. I had totally forgotten about the date being an available format for `datasets`. It is now formatted as a `date64` field with the format `%Y`

Awesome, this looks good to me. Thanks again!
